name: Test and Run

on:
  pull_request: 
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test_and_run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4.7.0
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python -m spacy download en_core_web_sm

    - name: Test with pytest
      run: |
        pytest